name: Auto Merge Release PR

on:
  pull_request:
    branches:
      - main

permissions:
  contents: write
  pull-requests: write

jobs:
  auto-merge:
    # Only run for the "Version Packages" PR created by Changesets
    if: startsWith(github.head_ref, 'changeset-release/')
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v4

      - name: Approve and Auto-Merge
        env:
          GH_TOKEN: ${{ secrets.GH_TOKEN_FOR_CI }}
        run: |
          gh pr merge --squash --auto "${{ github.event.pull_request.html_url }}"
